import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00174b",
        "tertiary-container": "#bc4800",
        "on-primary": "#ffffff",
        "outline": "#737686",
        "on-tertiary-fixed": "#360f00",
        "error": "#ba1a1a",
        "on-primary-container": "#eeefff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e2e7ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005137",
        "surface-dim": "#d2d9f4",
        "on-surface": "#131b2e",
        "on-secondary-container": "#00714e",
        "on-background": "#131b2e",
        "on-tertiary-fixed-variant": "#7d2d00",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "primary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#eef0ff",
        "surface": "#faf8ff",
        "tertiary": "#943700",
        "surface-container-highest": "#dae2fd",
        "tertiary-fixed": "#ffdbcd",
        "inverse-primary": "#b4c5ff",
        "primary-container": "#2563eb",
        "on-tertiary-container": "#ffede6",
        "background": "#faf8ff",
        "inverse-surface": "#283044",
        "on-secondary-fixed": "#002114",
        "surface-container": "#eaedff",
        "primary": "#004ac6",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#68dba9",
        "tertiary-fixed-dim": "#ffb596",
        "secondary-fixed": "#85f8c4",
        "outline-variant": "#c3c6d7",
        "surface-bright": "#faf8ff",
        "surface-tint": "#0053db",
        "on-error": "#ffffff",
        "secondary": "#006c4a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        lg: "24px",
        sm: "8px",
        gutter: "24px",
        "container-max": "1280px",
        md: "16px",
        xs: "4px",
        xl: "40px",
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
